openapi: 3.1.0
info:
  title: iShop API
  description: This is the OpenAPI for the backend iShop API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /auth/login:
    post:
      summary: Login
      description: Login user into the system
      operationId: login
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Username or email is required
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid credentials
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
  /auth/register:
    post:
      summary: Register
      description: Register user into the system
      operationId: register
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered. Please verify your email.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Username, email, and password are required
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User with this email or username already exists
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
  /products:
      get:
        summary: Get all products
        description: Get all products
        operationId: getProducts
        tags:
          - Products
        security:
          - basicAuth: [ ]
        parameters:
          - name: page
            in: query
            description: Page number for pagination
            required: false
            schema:
              type: integer
              minimum: 1
              default: 1
          - name: limit
            in: query
            description: Number of products per page
            required: false
            schema:
              type: integer
              minimum: 1
              maximum: 100
              default: 10
        responses:
          '200':
            description: List of products retrieved successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    products:
                      type: array
                      items:
                        $ref: '#/components/schemas/Product'
                    pagination:
                      $ref: '#/components/schemas/Pagination'
          '400':
            description: Bad request - invalid parameters
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
          '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'



components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer

  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
      required:
        - password
      oneOf:
        - required: [email]
        - required: [username]
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [user, admin, workers]
      required:
        - email
        - username
        - password
    Product:
      type: object
      properties:
        id:
          type: integer
          description: Unique product identifier
        name:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        price:
          type: number
          format: float
          description: Product price
        category:
          type: string
          description: Product category
        imageUrl:
          type: string
          format: uri
          description: URL to product image
        inStock:
          type: boolean
          description: Whether the product is in stock
        quantity:
          type: integer
          description: Available quantity
        createdAt:
          type: string
          format: date-time
          description: Product creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Product last update timestamp
      required:
        - id
        - name
        - price
        - category
        - inStock

    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
          description: Current page number
        totalPages:
          type: integer
          description: Total number of pages
        totalItems:
          type: integer
          description: Total number of products
        itemsPerPage:
          type: integer
          description: Number of items per page
        hasNextPage:
          type: boolean
          description: Whether there is a next page
        hasPreviousPage:
          type: boolean
          description: Whether there is a previous page
      required:
        - currentPage
        - totalPages
        - totalItems
        - itemsPerPage

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
      required:
        - error
